title: Blog de Federich
author: @fdegiovanni
email: federicoadegiovanni@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Blog personal de tecnologia, desarrollo de software, buenas practicas y otras cosillas
  
# social links
twitter_username: carailuso # DO NOT include the @ character, or else the build will fail!
github_username:  fdegiovanni # DO NOT include the @ character, or else the build will fail!
instagram_username: fddgvnn

show_excerpts: true # set to false to remove excerpts on the homepage
